# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Chq01A7SYJDtvsvec5ijm6Qmc_ocnkiB

# Início
"""

# @title
!pip install openai-whisper
# biblioteca que contém a rede neural treinada para áudio
import whisper
# download e carregamento na memória do Colab os pesos do modelo, "base" atende a esta demanda simplificada
# Outras opções para teste: tiny, base, small, medium, large)
model = whisper.load_model("base")

from google.colab import files
uploaded = files.upload()

# Isso vai extrair o nome do arquivo que você acabou de subir automaticamente
nome_do_arquivo = list(uploaded.keys())[0]
print(f"Arquivo pronto para uso: {nome_do_arquivo}")

# Usamos a variável 'nome_do_arquivo' definida na célula anterior
print("Transcrevendo... por favor aguarde.")
# whisper converte o áudio em uma formato que a rede neural entenda,advinha a lingua e traduz o texto em tokens e depois em texto legível
result = model.transcribe("/content/audio-estudo.mp3")

print("-" * 30)
print("Texto Transcrito:")
# reultado da transcrição completa
print(result["text"])
# idiona
print(result["language"])
# tempo de início, fim e texto
print(result["segments"])