# -*- coding: utf-8 -*-
"""projeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Chq01A7SYJDtvsvec5ijm6Qmc_ocnkiB

# Início
"""

# @title
!pip install openai-whisper
# biblioteca que contém a rede neural treinada para áudio
import whisper
# download e carregamento na memória do Colab os pesos do modelo, "base" atende a esta demanda simplificada
# Outras opções para teste: tiny, base, small, medium, large)
model = whisper.load_model("base")

from google.colab import files
uploaded = files.upload()

# Isso vai extrair o nome do arquivo que você acabou de subir automaticamente
nome_do_arquivo = list(uploaded.keys())[0]
print(f"Arquivo pronto para uso: {nome_do_arquivo}")

# Usamos a variável 'nome_do_arquivo' definida na célula anterior
print("Transcrevendo... por favor aguarde.")
# whisper converte o áudio em uma formato que a rede neural entenda,advinha a lingua e traduz o texto em tokens e depois em texto legível
result = model.transcribe("/content/audio-estudo.mp3")

print("-" * 30)
print("Texto Transcrito:")
# reultado da transcrição completa
print(result["text"])
# idiona
print(result["language"])
# tempo de início, fim e texto
print(result["segments"])

# Gerar legendas .srt

import datetime

def formatar_tempo(segundos):
    """Converte segundos para o formato de legenda SRT: HH:MM:SS,mmm"""
    td = datetime.timedelta(seconds=segundos)
    # Formata para string e ajusta os milissegundos
    tempo_str = str(td)
    if "." in tempo_str:
        tempo_str = tempo_str.replace(".", ",")
        return tempo_str[:-3] # Remove os últimos dígitos para ficar com 3 casas decimais
    return tempo_str + ",000"

# Abrindo o arquivo para escrita
with open("legendas.srt", "w", encoding="utf-8") as f:
    for i, segmento in enumerate(result["segments"]):
        inicio = formatar_tempo(segmento["start"])
        fim = formatar_tempo(segmento["end"])
        texto = segmento["text"].strip()

        # Estrutura do arquivo SRT:
        # 1. Número do segmento
        # 2. Tempo de início --> Tempo de fim
        # 3. Texto
        # 4. Linha em branco
        f.write(f"{i + 1}\n")
        f.write(f"{inicio} --> {fim}\n")
        f.write(f"{texto}\n\n")

print("Arquivo 'legendas.srt' gerado com sucesso!")

# tradução de texto nativa do Whisper

# O parâmetro task="translate" diz ao Whisper para traduzir para o inglês
print("Traduzindo áudio para inglês...")
result_en = model.transcribe(nome_do_arquivo, task="translate")

# Salvando a transcrição em inglês
with open("transcription_en.txt", "w", encoding="utf-8") as f:
    f.write(result_en["text"])

print("Tradução concluída! Arquivo transcription_en.txt gerado.")